FROM mcr.microsoft.com/dotnet/core/sdk:2.1 as build
WORKDIR /src
COPY mymicroservice1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app
FROM mcr.microsoft.com/dotnet/core/sdk:2.1
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "mymicroservice1.dll"]